let foodpandaLinks = [
  {
    branchName: "TG HQ",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/a7u5",
    latitude: 13.8056359,
    longitude: 100.562122,
    distance: 0,
    isOpen: false,
  },
  {
    branchName: "Don Muang",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/sz7t",
    latitude: 13.8975469,
    longitude: 100.5896402,
    distance: 0,
    isOpen: true,
  },
  {
    branchName: "Rak Khun Thao FA Building",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/iksa",
    latitude: 13.8974886,
    longitude: 100.5903395,
    distance: 0,
    isOpen: true,
  },

  {
    branchName: "Sirindhorn Hospital",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/yfpt",
    latitude: 13.7200806,
    longitude: 100.7071465,
    distance: 0,
    isOpen: true,
  },
  {
    branchName: "Fashion Island",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/ovan",
    latitude: 13.8246644,
    longitude: 100.678121,
    distance: 0,
    isOpen: true,
  },
  {
    branchName: "Vajira Hospital",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/gew0",
    latitude: 13.7804774,
    longitude: 100.5084252,
    distance: 0,
    isOpen: true,
  },

  {
    branchName: "B.Care Medical Center",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/qpz6",
    latitude: 13.9434091,
    longitude: 100.623992,
    distance: 0,
    isOpen: true,
  },
  {
    branchName: "Ladprao Hospital",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/g7g3",
    latitude: 13.7788968,
    longitude: 100.6235611,
    distance: 0,
    isOpen: true,
  },
  {
    branchName: "Or Tor Kor Market",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/ldwj",
    latitude: 13.797043,
    longitude: 100.54689,
    distance: 0,
    isOpen: true,
  },
  {
    branchName: "Chulabhorn Hospital",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/vvpb",
    latitude: 13.8809797,
    longitude: 100.5781207,
    distance: 0,
    isOpen: true,
  },
  {
    branchName: "Coffee Corner THAI Office",
    riderLink: "https://www.foodpanda.co.th/th/restaurant/ulj3",
    latitude: 13.8053221,
    longitude: 100.5611411,
    distance: 0,
    isOpen: true,
  },
];
